---
title: "report.rmd"
author: "Noah Suter"
date: "2023-02-27"
output: html_document
---

# AGDS Report

## Report Exercise 1


### Task 1
```{r}
list.files('../AGDS/Data') #listing the files to find the right data
```

```{r}
database_s1<- readr::read_csv("../AGDS/Data/data_csv_exercise_1.csv") # reading the .csv into R
```

### Task 2

```{r}
sample_data_RR <- dplyr::mutate(database_s1, log_response_ratio = log((`increased CO2`/`ambient CO2`))) #calculate the RR and add as a new column
```

```{r} 
sample_date_yearly <-  sample_data_RR|> #create new table
  dplyr::group_by(Experiment, `Sample date (year)`) |> #aggregate by experiment with subgroup sample date (in years)
  dplyr::summarise(`log_response_ratio_mean` = mean(`log_response_ratio`)) #calculating the mean of RR within the defined groups
```

```{r}
knitr::kable(sample_date_yearly)
#present the results as knitr::kable()
```

### Task 3
```{r}
phase_1 <- dplyr::filter(sample_data_RR, `Time (years)` <3) |>
  dplyr::summarise(`log_response_ratio_mean` = mean(`log_response_ratio`)) #aggregate the RR of phase 1
```

```{r}

phase_2 <- dplyr::filter(sample_data_RR, `Time (years)` >=3 & `Time (years)`<6) |>
  dplyr::summarise(`log_response_ratio_mean` = mean(`log_response_ratio`)) #aggregate the RR of phase 2
```

```{r}
phase_3 <- dplyr::filter(sample_data_RR, `Time (years)` >=6) |>
  dplyr::summarise(`log_response_ratio_mean` = mean(`log_response_ratio`)) #aggregate the RR of phase 3
```

```{r}
all_phases <- rbind(phase_1, phase_2, phase_3) #bind all 3 phase tables to one table
all_phases <- dplyr::mutate(all_phases,`Phase` = c("early phase (<3 years since start)", "mid phase (3-6 years since start", "late phase (>6 years since start)" )) #add a column with the phase description
```

```{r}
all_phases <- dplyr::select(all_phases,`Phase`, everything()) #moving the phase column to position one
```

```{r}
knitr::kable(all_phases) #present the results as knitr::table
```





